"""empty message

Revision ID: c3951cef308d
Revises: 6b060f49ea54
Create Date: 2022-03-14 17:58:42.132733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3951cef308d'
down_revision = '6b060f49ea54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('image', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'image')
    # ### end Alembic commands ###
